# to install: rename this file to .local_client_id.yaml and use data from google console project
id: xxxxxxxx-m6kqsd2nvggdg2rrge5h9j1rbhfalia3.apps.googleusercontent.com
secret: RE6C1zDMZOJUCwDfu-xxxx