name: tekartik_googleapis_auth
version: 0.0.2
description: Allow login with a specific account
environment:
  sdk: ^3.5.0
dependencies:
  googleapis: '>=0.32.0'
  googleapis_auth: '>=0.2.3'

dev_dependencies:
  test: '>=0.12.16'
