name: tekartik_googleapis_auth
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  googleapis: any
  googleapis_auth: any
dev_dependencies:
  test: any
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter
